Tiles branch
inf112-v19/Bender pull request #28
Opened 2019-02-13 19:27 UTC by AndreasCanAtakan

Finished first draft of tile classes

2019-02-13 19:39 UTC, RuneThe approved these changes

2019-02-13 19:41 UTC, petterdaae requested changes
Could you add public/private on the methods that miss it in the Tile class? :)

2019-02-13 20:55 UTC, AndreasCanAtakan commented
@petterdaae you're right, totally forgot :p Just committed a new version with the public/private key-words in Tile

2019-02-13 20:57 UTC, RuneThe approved these changes

2019-02-14 06:46 UTC, petterdaae approved these changes

2019-02-21 13:46 UTC, merged