Boardloader
inf112-v19/Bender pull request #85
Opened 2019-04-04 20:05 UTC by AndreasCanAtakan

@RuneThe , @petterdaae 

Hei :)

Jeg har skrevet ferdig et første utkast av BoardLoader klassen, men jeg har måttet endre litt på Tile pakken og parameter-settet til csv filene vi leser fra.

Jeg har lagt til en ny parameter i TileAssemblyLine, av typen boolean, som sier om tile-en er en express tile eller ikke (dobbel hastighet eller ikke). I tillegg har jeg laget en del nye klasser;
* TileAssemblyLineMerge
* TileAssemblyLineSplit
* TileAssemblyLineTurn
Alle disse klassene extender TileAssemblyLine, og kan bruks for de forskjellige variantene av TileAssemblyLine.

Med tanke på oppsettet for parameterne i CSV filen (parameterne som er delt med | ), har jeg gjort noen nye antakelser;
* Første parameter er som før : bestemmer tile type
* Andre parameter er som før : bestemmer flag ordinal
* Tredje parameter er endret : jeg og Rune ble enig om å endre formatet til et firesifret binærtall
           (De neste gjelder bare for TileAssemblyLines)
* Fjerde parameter er som før : bestemmer TileAssemblyLine type
* Femte parameter er nytt : bestemmer om Tile er av type 'EXPRESS'
           (Det neste gjelder bare for TileAssemblyLineTurn)
* Sjette parameter er nytt : bestemmer snu-retning til Tile

Ser dette ut som en grei struktur?

P.S.
Jeg har ikke skriverett til Google Sheet dokumentet på Google drive, så hvis dette ser ut som en grei konvensjon for parameterne, kan vi oppdatere Google dokumentet.

2019-04-05 06:21 UTC, RuneThe approved these changes

2019-04-05 13:31 UTC, petterdaae requested changes
Høres veldig bra ut! Men når jeg puller branches og kjører `mvn clean install`, så kompilerer ikke prosjektet. Kan du fikse dette?

2019-04-06 10:42 UTC, AndreasCanAtakan commented
@petterdaae 
Nå har jeg sett litt på koden, og maven bygger helt fint på min maskin. Kan du prøve på nytt hos deg?

2019-04-07 13:30 UTC, petterdaae approved these changes

2019-04-07 15:23 UTC, dsp0011 approved these changes

2019-04-07 16:56 UTC, merged